// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RPDControlSystem.Models.RPD;
using RPDControlSystem.Storage;
using System;

namespace RPDControlSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180510221937_AddRequiredTagForDisciplineCode")]
    partial class AddRequiredTagForDisciplineCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("RPDControlSystem.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseName")
                        .IsRequired();

                    b.Property<string>("Directory")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("DirectionCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DirectionCode");

                    b.ToTable("Competence");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.Direction", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Qualification");

                    b.HasKey("Code");

                    b.ToTable("Direction");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.Discipline", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Code");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.DisciplineCompetence", b =>
                {
                    b.Property<int>("DisciplineInfoId");

                    b.Property<int>("CompetenceId");

                    b.HasKey("DisciplineInfoId", "CompetenceId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("DisciplineCompetence");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.DisciplineInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisciplineCode")
                        .IsRequired();

                    b.Property<int>("DisciplineType");

                    b.Property<string>("PlanCode")
                        .IsRequired();

                    b.Property<int?>("WorkPlanId");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineCode");

                    b.HasIndex("PlanCode");

                    b.HasIndex("WorkPlanId");

                    b.ToTable("DisciplineInfo");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.Plan", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EducationForm");

                    b.Property<int>("EducationFormId");

                    b.Property<string>("ProfileCode")
                        .IsRequired();

                    b.HasKey("Code");

                    b.HasIndex("ProfileCode");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.Profile", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DirectionCode")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Code");

                    b.HasIndex("DirectionCode");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.ProfileCompetence", b =>
                {
                    b.Property<string>("ProfileCode");

                    b.Property<int>("CompetenceId");

                    b.HasKey("ProfileCode", "CompetenceId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("ProfileCompetence");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.Competence", b =>
                {
                    b.HasOne("RPDControlSystem.Models.RPD.Direction", "Direction")
                        .WithMany("Competencies")
                        .HasForeignKey("DirectionCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.DisciplineCompetence", b =>
                {
                    b.HasOne("RPDControlSystem.Models.RPD.Competence", "Competence")
                        .WithMany("Disciplines")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RPDControlSystem.Models.RPD.DisciplineInfo", "DisciplineInfo")
                        .WithMany("Competencies")
                        .HasForeignKey("DisciplineInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.DisciplineInfo", b =>
                {
                    b.HasOne("RPDControlSystem.Models.RPD.Discipline", "Discipline")
                        .WithMany("DisciplinesInfo")
                        .HasForeignKey("DisciplineCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RPDControlSystem.Models.RPD.Plan", "Plan")
                        .WithMany("Disciplines")
                        .HasForeignKey("PlanCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RPDControlSystem.Models.File", "WorkPlan")
                        .WithMany()
                        .HasForeignKey("WorkPlanId");
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.Plan", b =>
                {
                    b.HasOne("RPDControlSystem.Models.RPD.Profile", "Profile")
                        .WithMany("Plans")
                        .HasForeignKey("ProfileCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.Profile", b =>
                {
                    b.HasOne("RPDControlSystem.Models.RPD.Direction", "Direction")
                        .WithMany("Profiles")
                        .HasForeignKey("DirectionCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RPDControlSystem.Models.RPD.ProfileCompetence", b =>
                {
                    b.HasOne("RPDControlSystem.Models.RPD.Competence", "Competence")
                        .WithMany("Profiles")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RPDControlSystem.Models.RPD.Profile", "Profile")
                        .WithMany("Competencies")
                        .HasForeignKey("ProfileCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
